### ISSUE TITLE
vxTikTok broken

### ISSUE THREAD

**Issue by yeeterlol** [dylanpdx/vxtiktok#142]
![image](https://github.com/dylanpdx/vxtiktok/assets/81702700/485c28a5-8747-4324-9501-819a94774225)
videos are broken now due to the new API changes

**Comment by foodornt** [comment]
I can confirm

**Comment by dylanpdx** [comment]
Will take a look

**Comment by Delphox** [comment]
yt-dlp updated yesterday with support for all formats again using the web API, so updating yt-dlp and reverting the previous temporary fix should hopefully fix it.

**Comment by kpopdev** [comment]
https://www.vxtiktok.com/@twice_tiktok_official/video/7372070699491511560 this link not working on discord its broken

**Comment by kpopdev** [comment]
@dylanpdx please check https://www.vxtiktok.com/@twice_tiktok_official/video/7372070699491511560

**Comment by dylanpdx** [comment]
Looks like this will be a slightly trickier fix, but I'll see what I can do

**Comment by dylanpdx** [comment]
Videos should be fixed. Slideshows still are not working (refer to #136)
Will close if there are no major issues

**Comment by slisaasquatch** [comment]
The videos now embed, but after the fix, the embedded videos can no longer play on iOS. They play on desktop just fine.

**Comment by ruukulada** [comment]
Wondering if we can switch to [https://www.tfxktok.com](https://www.tfxktok.com) which works on iOS?

**Comment by Harest** [comment]
Seems the issue is back. At least on Discord currently, the videos are missing from the embeds.
